### ISSUE TITLE
Cannot rename directory with file on OS standby list (passthrough and related file systems)

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#45]
I found this bug when testing my application compiled against WinFsp, and it can be reproduced with the bundled `passthrough-fuse`.

To reproduce it, first create two directories `a` and `b` in the mounted filesystem and copy a music file under `a`. Then open it with some media player and then close it. Try moving the directory `a` into `b` and you will get access denied.

My own tracing logs suggest that some files are not closed. Specifically, the `open` calls are not balanced by `release` calls. Since it can be reproduced with `passthrough-fuse`, it must be a problem with WinFsp, either in its core or in its fuse layer.

**Comment by billziss-gh** [comment]
I agree. The problem happens when there is a sharing violation while opening an oplock'ed file (oplocks are "opportunistic locks" and are different to normal file locks).

This is a bug that had somehow escaped my testing with MEMFS, because MEMFS is forgiving with files that remain open. I actually discovered it myself while testing the passthrough and passthrough-fuse file systems. I believe it was fixed in commit bfc41127d03c7f14a25f03bef5bef6c3f1fe81ff.

Thanks for the great bug report. Please retest after RC2 is out and let me know if the problem persists.

**Comment by billziss-gh** [comment]
BTW, @netheril96, if you wish I can provide a latest build of WinFsp that has this and the others problems we have discussed fixed. This is not the final RC2 build, but it is very close.

The only caveat is that the driver in this build would only be cross signed with my EV certificate, which allows you to load it on all versions of Windows except Win10 Anniversary Edition (new install -- upgrade still works and cross-signed drivers get loaded) and Server 2016.

Let me know.

**Comment by netheril96** [comment]
Thanks for your suggestion, but I am on Win10 Anniversary Edition. Besides, I've already implemented workarounds that will continue to work when you fix the bugs. This bug won't require change to my code or recompilation either so testing against RC1 is fine.

**Comment by billziss-gh** [comment]
Understood. In this case I am closing this as we believe it fixed in RC2. Please reopen and let me know if the problem persists.

**Comment by billziss-gh** [comment]
Hi, @netheril96. The RC2 has now been released. Please download and test whether this problem persists.

https://github.com/billziss-gh/winfsp/releases/download/v1.0RC2/winfsp-1.0.17039.msi

**Comment by netheril96** [comment]
Sadly the bug persists.

**Comment by billziss-gh** [comment]
Ok, I am doing some testing and I thinking this is not actually related to commit bfc41127d03c7f14a25f03bef5bef6c3f1fe81ff. I am reopening for now.

**Comment by billziss-gh** [comment]
BTW, there is a utility called [RAMMap](https://technet.microsoft.com/en-us/sysinternals/rammap.aspx?f=255&MSPPError=-2147217396) from Sysinternals.

One of its useful features is that it can force Windows to empty its "Standby" list. This usually results in the OS releasing all extra file references kept after a file is closed, thus sending us the `CLOSE` and allowing the directory to be renamed.

This is not a general solution of course. Just something that I use to test such problems.

**Comment by billziss-gh** [comment]
I now have an experimental fix and some tests for this issue.

The issue happens because there is a mismatch between file system semantics as interpreted by user mode and file system semantics as interpreted by the kernel. In user mode a file has handles and when all handles are closed the file is no longer in use (this is not entirely true, file mappings keep a file around even without any handles). In kernel mode a file object has both handles and references: when the handles are gone a `CLEANUP` IRP is sent, when all the references are gone a `CLOSE` IRP is also sent (`CLEANUP` always precedes `CLOSE` for the same `FILE_OBJECT`).

The FUSE layer issues a `close` during receipt of the `CLOSE` IRP. It can be argued that this breaks Windows file system semantics and that the `close` should be issued during receipt of the `CLEANUP`. The reason that this is not done, is to cleanly support `READ` / `WRITE` IRP's that arrive after `CLEANUP`. These are actually quite common: for example, they happen whenever a cached file is written and closed, the OS will `CLEANUP` the file at `CloseHandle` time and then at a later time the OS Lazy Writer will send delayed `WRITE` IRP's and then `CLOSE` the file.

One potential fix that I contemplated was to actually issue the `close` at `CLEANUP` time and then temporarily re-`open` the file if I get any `READ` or `WRITE` IRP's at a later time. There are a lot of reasons that I do not think this is a good idea.

The fix I am focusing on is slightly different. It focuses on the `Rename` operation only: whenever the FSD receives a `Rename` for a directory, it checks to see if there are any files underneath it that have no handles, but are still referenced by the OS and instructs the OS to flush those files and relinquish them.

Here are the reasons that I consider this fix "experimental":

- It only targets the `Rename` operation. A FUSE file system that opens its files with `FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE` should not have any issues with operations other than `Rename` but I may be missing something.

- Despite the name of the DDI used to instruct the OS to relinquish files (`MmForceSectionClosed`), it is more like: "Can you please dereference my file? Pretty please?"

- The fix can likely be further improved. [E.g. should we use `MmCanFileBeTruncated` instead of `MmDoesFileHaveUserWritableReferences` to detect file mappings?]

I will continue to test this fix.

**Comment by netheril96** [comment]
Dokany has both cleanup and close in its callback, and WINFSP could do the same. What remains problematic would be the fuse interface. You might either add extensions to the `fuse_operations`, or let the reopening handled in user space by the fuse dll.

**Comment by billziss-gh** [comment]
I believe the solution that I am proposing and have implemented is superior for a number of reasons:

- It works for the passthrough and related file systems without any changes.

- It works for the FUSE layer without any changes.

- Reopening a file during delayed `READ` and `WRITE` has multiple issues: (1) It makes the file system terribly slow, when a file is constantly reopened and closed to service a delayed operation. [If the file system tries to be smart about it and only reopen the file, but never close it (until `CLOSE` time), you still have the `RENAME` issue we are discussing.] (2) It is very hard to ensure proper file system semantics in all cases and in the face of race conditions between delayed `READ`, `WRITE` and other operations (which are not currently an issue).

[It should be noted here that only file systems that use NTFS (or other Windows file system) as their storage medium exhibit this issue. For example, MEMFS and my own secfs, which implements POSIX file system semantics, do not exhibit this issue.]

**Comment by billziss-gh** [comment]
I have now tested this change thoroughly and have merged with the release/1.0 branch. It will be available at the next release. I am happy to make a (fully signed) prerelease available to you for testing if you want.

**Comment by netheril96** [comment]
Thanks. How may I get the prerelease?

**Comment by billziss-gh** [comment]
You mentioned earlier you have Win10 Anniversary Update. Is it a new install or an upgrade from a previous Win10 install? I am asking to see whether cross signing with my EV certificate will be enough or whether I need to submit the driver for "attestation" signing to Microsoft (which I can happily do, I would just rather avoid it if it is not necessary).

**Comment by netheril96** [comment]
I have rolled back the Anniversary Update since it denied me access to HFS+ volumes.

**Comment by billziss-gh** [comment]
Ok, a cross-signed build should work then. I will make it available to you tomorrow.

**Comment by billziss-gh** [comment]
Here is a latest build that includes this fix:

http://www.secfs.net.s3.amazonaws.com/winfsp/winfsp-1.0.17044.msi

Let me know the results.
